version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_punto_de_venta
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - .:/var/www/
    networks:
      - app-network
    depends_on:
      - db
    working_dir: /var/www


  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf/:/etc/nginx/conf.d/
      - ./:/var/www/
    networks:
      - app-network


  db:
    image: mysql:5.7.22
    container_name: db_punto_de_venta
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: punto_de_venta
      MYSQL_ROOT_PASSWORD: test
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
