<?php


namespace App\Repositories\Eloquent;

use App\Utils\UtilsKey;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

abstract class MovementRepository extends BaseRepository
{
    protected string $type;

    /**
     * OfficeRepository constructor.
     * @param Model $model
     */
    public function __construct(Model $model)
    {
        parent::__construct($model);
    }

    /**
     * @inheritDoc
     */
    public function all(): Collection
    {
        $store_id = session(UtilsKey::CURRENT_STORE_ID);
        return $this->model->where([
            ['store_id', $store_id],
            ['type', $this->type]
        ])->get();
    }

    public function create(array $attributes): Model
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
