<?php


namespace App\Repositories\Eloquent;

use App\Utils\UtilsKey;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

abstract class MovementRepository extends BaseRepository
{
    protected string $type;

    /**
     * OfficeRepository constructor.
     * @param Model $model
     */
    public function __construct(Model $model)
    {
        parent::__construct($model);
    }

    public function all(): Collection
    {
        $movements = parent::all();
        return $movements->filter(function ($movement) {
            return $movement->type === $this->type;
        });
    }

    public function create(array $attributes): Model
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
